name: Run Lemmy Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy_lemmy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: lemmy.yml
          directory: ./
          key: ${{secrets.ansible_ssh_private_key}}
          inventory: ${{secrets.ansible_inventory}}
